name = "Blacked Aeronautics"
author = "BlackSoul1337; based on Aeronautics - Create Customised"
version = "1.1.4-ely.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a4ec42202cb134ff58ab0bbf8b5a4d4db94d3508daeaf8fb9ee3024a3f27362"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
acceptable-game-versions = ["1.21.1"]
no-internal-hashes = true
