name = "Blacked Aeronautics"
author = "BlackSoul1337; based on Aeronautics - Create Customised"
version = "1.1.4-ely.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e07c3aba198f6cb28c50d940d743b6cc8af9a68770458538130404b199a2dfc8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
acceptable-game-versions = ["1.21.1"]
no-internal-hashes = true
