#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jul 16 20:24:00 GMT 2026
allowUnknownShaders=false
colorSpace=DCI_P3
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=5
shaderPack=photon_v1.2a + Clrwl_1.0.4.zip
